# Generated by Django 5.2.1 on 2025-06-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('ciphertext', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('wrap_key', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
