# Generated by Django 5.2.1 on 2025-06-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150, unique=True)),
                ('ciphertext', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('wrap_key', models.BinaryField(help_text='Clave simétrica cifrada para el dentista A')),
                ('wrap_key_b', models.BinaryField(help_text='Clave simétrica cifrada para el dentista B')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
