# Generated by Django 5.2.1 on 2025-06-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedrecord',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='encryptedrecord',
            name='patient_name',
            field=models.CharField(default='Juan Escutia Torres', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
