# Generated by Django 5.2.1 on 2025-06-11 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_encryptedrecord_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedrecord',
            name='nonce_a',
            field=models.BinaryField(blank=True, help_text='Nonce para AES-GCM con el dentista A', null=True),
        ),
        migrations.AddField(
            model_name='encryptedrecord',
            name='nonce_b',
            field=models.BinaryField(blank=True, help_text='Nonce para AES-GCM con el dentista B', null=True),
        ),
        migrations.AddField(
            model_name='encryptedrecord',
            name='sender_pub_a',
            field=models.BinaryField(blank=True, help_text='Clave pública efímera del emisor para A', null=True),
        ),
        migrations.AddField(
            model_name='encryptedrecord',
            name='sender_pub_b',
            field=models.BinaryField(blank=True, help_text='Clave pública efímera del emisor para B', null=True),
        ),
        migrations.AlterField(
            model_name='encryptedrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
